[package]
name = "tasks_server"
version = "0.1.0"
authors = ["Nathan Dullea <njdullea@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-cors = "0.5.3"
